### ISSUE TITLE
issues: kern/arm/gic.cpp

### ISSUE THREAD

**Issue by hello-os** [kernkonzept/fiasco#1]
why returned?
it won't work,if i want to use Gic::set_mode.

352 Gic::set_mode(Mword pin, Mode m) override 
353 { 
354   return 0;

**Comment by icedieler** [comment]
Hi,

you are right. To configure the interrupt correctly you also need to set the mode.

It looks like the return was introduced to keep some ARM9 setups working and because of some other architectural requirements.

Do you need this right now? You could try to remove the early return and see if it is working for you.

**Comment by hello-os** [comment]
i'am using arm64. I have configured irq mode(example:**Resource.irq0 = Res.irq(54, Io.Resource.Irq_type_level_high);**) in io.cfg file before.
But the interrupt didn't come.
I found another way , **Icu::set_mode()**--->Gic::set_mode , to configure interrupt mode by viewing code. I tried to remove the early return,and it worked.
I don't think it's a good idea to call icu::set_mode() directly.That configuring file(io.cfg) to set intrrupt mode would be better.
Therefore,i have two questions.
1.Could i just modify file(io.cfg) to configure interrupt mode without calling function?
2. even though some other architecture,how do they configure interrupt mode(edge or level trriger)?

**Comment by icedieler** [comment]
You io.cfg file is just a description of physical devices and their resources. Io doesn't interprets or uses this information but instead a client (e.g. driver) must use this information accordingly.

So the answers to your questions are:
1. No. That's not enough.
2. This is done via the ICU interface by the clients.

**Comment by hello-os** [comment]
Thank you for reply.
As you say,the io.cfg file is just a description,and i must use the ICU interface to configure interrupt.
How to understand the parameter(e.g. Io.Resource.Irq_type_level_high)?And where it will be used?
the detail example from pkg/io/io/config/plat-imx6/hw_devices.io :
  **usdhc3 = Io.Hw.Device(function()
    compatible = {"fsl,imx6q-usdhc"};
    Resource.reg0 = Res.mmio(0x2198000, 0x219bfff);
    Resource.irq0 = Res.irq(56, Io.Resource.Irq_type_level_high);
    Property.flags = Io.Hw_device_DF_dma_supported;
  end);**

**Comment by icedieler** [comment]
Sorry, I have to correct my answer a little bit. Usually Io tries to configure IRQs according to the information stated by the device tree. A client may use the ICU interface to reconfigure the IRQ using the set_mode() function.

For each device Io stores the resources of that device. For an IRQ resource the IRQ number and the mode (e.g. Irq_type_level_high) is stored. When a client then binds the IRQ, Io uses that information and sets the mode (see the [API doc for L4::Icu::bind](https://l4re.org/doc/classL4_1_1Icu.html#details))

**Comment by hello-os** [comment]
It seems that the API doc for L4::Icu::bind doesn't use 'Io.Resource.Irq_type_level_high' but '56(irqnum)'.
e.g. Resource.irq0 = Res.irq(56, Io.Resource.Irq_type_level_high);
here are the API,

**l4_msgtag_t L4::Icu::bind ( unsigned  irqnum, L4::Cap< Triggerable >  irq, l4_utcb_t * | utcb = l4_utcb()) throw ( )**

you said that When a client then binds the IRQ, Io uses that information and sets the mode.I do not get it. Would you mind showing me the code? I really appreciate it.

**Comment by icedieler** [comment]
That depends on the type of IRQ. You can find an example for a kernel IRQ [here](https://github.com/kernkonzept/io/blob/master/io/server/src/irqs.cc#L23)

**Comment by hello-os** [comment]
Thank you.
