### ISSUE TITLE
arm/fpu: eager FPU switching triggers assertion

### ISSUE THREAD

**Issue by skalk** [kernkonzept/fiasco#3]
After updating Fiasco.OC to the current state on Github (commit-id 4367c50b1df878604b9833d4b41ae311d6e12e03), I've tested the new configuration option to always switch the FPU eagerly, because our user-level components make heavy use of the FPU anyway. But when the configuration option "Enable lazy FPU switching" is not set, the kernel runs into an assertion at the very beginning: `src/kern/arm/32/fpu-arm.cpp:327`. I have tested it on i.MX6 Quad Sabrelite.

**Comment by icedieler** [comment]
Thanks for reporting this issue. I can reproduce it and we will have a look into it. Right now eager FPU switching is only supposed to work on x86_64.

**Comment by skalk** [comment]
Thanks for the fast reaction!

**Comment by icedieler** [comment]
This should be fixed now with commit 20ddd811619408ff63f9d07f323606f36401184d. Feel free to give it a try. I will close this issue now.
