### ISSUE TITLE
ARM link error with binutils 2.36.1

### ISSUE THREAD

**Issue by cproc** [kernkonzept/fiasco#4]
When building Fiasco.OC for ARM with binutils 2.36.1 (as provided by Ubuntu 21.04), a link error occurs:

```
  ==> Linking fiasco.debug
arm-linux-gnueabihf-ld: cannot use executable file 'bootstrap.fiasco.o' as input to a link
```

The error is related to this binutils change: https://sourceware.org/bugzilla/show_bug.cgi?id=26047

**Comment by icedieler** [comment]
Hi,

thanks for reporting this. We will look into this issue. Does this happen for all supported ARM platforms or is this limited to a specific one?

Thanks,
Matthias

**Comment by cproc** [comment]
I have tried RealView PBX, i.MX8M and the default selection (ARM Integrator Platform), so at least those are affected.

**Comment by frankmehnert** [comment]
Thanks for the report. This is a known problem and we are working on it.

**Comment by icedieler** [comment]
Hi,
this actually is a more complicated problem than we originally anticipated. The kernel build system uses a feature that has been deprecated in binutils 2.35. Seems that Ubuntu couldn't wait and removed that feature in 2.36.
So I have to ask you for a little bit more patience while we change the way the kernel is linked.

**Comment by icedieler** [comment]
Hi,

Commit c8f2e0d3abcd7c09bc5882f16cfa671cb019c807 should fix the issue. If you can confirm this, I would close this issue.
Thanks again for reporting!

**Comment by cproc** [comment]
The commit solved the problem. Thanks.
