### ISSUE TITLE
Maybe bug this line in bitmap.cpp ?

### ISSUE THREAD

**Issue by ghost** [kernkonzept/fiasco#6]
https://github.com/kernkonzept/fiasco/blob/146fc857b682fc0170f2e07a41d34fc3b3ee3d44/src/lib/libk/bitmap.cpp#L141

Should be ` if (v & (1UL << b))` . Just like the function `atomic_get_and_set` above.

**Comment by frankmehnert** [comment]
Thank you very much for this report! We fixed this bug in our private branches. The change will be visible on the public branch within 1-2 weeks.

May I ask whether you found this bug by code inspection or if you have code which is affected by this bug?

**Comment by frankmehnert** [comment]
Thanks for the information!
