### ISSUE TITLE
Static Per_cpu objects constructed twice with !mp

### ISSUE THREAD

**Issue by vilaureu** [kernkonzept/fiasco#8]
Static `Per_cpu<>` objects are constructed twice in the same place if `CONFIG_MP` is disabled.

At least on x86, `Per_cpu_data::run_ctors` is called twice:
https://github.com/kernkonzept/fiasco/blob/b54215927b231227ed86439df5d2d9c0b8a6aaa4/src/kern/ia32/startup-ia32.cpp#L68
https://github.com/kernkonzept/fiasco/blob/b54215927b231227ed86439df5d2d9c0b8a6aaa4/src/kern/kernel_thread.cpp#L76

Without CONFIG_MP, `run_ctors` does not make use of the `Cpu_number` argument:
https://github.com/kernkonzept/fiasco/blob/b54215927b231227ed86439df5d2d9c0b8a6aaa4/src/kern/per_cpu_data.cpp#L170-L182

Therefore, the `Per_cpu<>` objects are constructed twice in the same place when they should only be constructed once or twice but in different locations (as it happens with `CONFIG_MP` enabled).

This problem also seems to occur with `Per_cpu_data::run_late_ctors` and `Per_cpu_data_alloc::alloc`.
I discovered this issue by observing that `Jdb_ipc_log_pm` was constructed twice.
https://github.com/kernkonzept/fiasco/blob/b54215927b231227ed86439df5d2d9c0b8a6aaa4/src/jdb/ia32/jdb_trace_set-ia32-ux.cpp#L128

I have not verified that the issue still persists with the newest commit on master but there are no relevant code changes as far as I can see.

**Comment by frankmehnert** [comment]
Thanks for the report! This is a known problem and we are working on a fix.

**Comment by icedieler** [comment]
Hi @vilaureu,
it turned out to be a lot harder to fix than first anticipated. And given the relevance of UP systems we decided to give this a very low prio. If you are running on an UP system you can set `MP_MAX_CPUS=1` during the configuration as a reasonable workaround.

I'll close this issue. Feel free to open it again if you happen to have new insights.

Regards,
