### ISSUE TITLE
Support for Containers?

### ISSUE THREAD

**Issue by matte21** [kernkonzept/fiasco#9]
Hello, sorry if this isn't the right channel to ask, but I couldn't find one that looked more suitable.

Does Fiasco (or the non-kernel components that run on top of it) support [containers](https://en.wikipedia.org/wiki/Containerization_(computing))?

If not, does Fiasco (or the non-kernel components that run on top of it) support concepts analogous to Linux [namespaces](https://man7.org/linux/man-pages/man7/namespaces.7.html) and [cgroups](https://en.wikipedia.org/wiki/Cgroups), to implement a container runtime on top of it?

**Comment by alacko** [comment]
Hi,

conceptually, L4Re and all the L4Re APIs are built in a way that each L4Re application is actually a container, i.e., all names are local and resources constraint. A runtime would be built upon this, and there are actually thoughts going into this.

Adam
